clinic = {
    "cat": [
        {
            "id": "6ad0f645",
            "treatment": "Cat Neutering",
            "desc": "",
            "price": 300000,
            "is_visible": True,
        },
        {
            "id": "24d84e44",
            "treatment": "Doctor's Consultation",
            "desc": "",
            "price": 250000,
            "is_visible": True,
        },
        {
            "id": "9343c583",
            "treatment": "USG",
            "desc": "",
            "price": 120000,
            "is_visible": True,
        },
        {
            "id": "817f5515",
            "treatment": "Cat Minor Surgery",
            "desc": "",
            "price": 350000,
            "is_visible": True,
        },
        {
            "id": "30a5e86a",
            "treatment": "Cat Major Surgery",
            "desc": "",
            "price": 600000,
            "is_visible": True,
        },
        {
            "id": "5f869d7c",
            "treatment": "Tricat Vaccination",
            "desc": "For Feline panleukopenia, Feline rhinotracheitis, Feline calicivirus",
            "price": 250000,
            "is_visible": True,
        },
        {
            "id": "846ced84",
            "treatment": "Tetracat Vaccination",
            "desc": "For Feline panleukopenia, Feline rhinotracheitis, Feline calicivirus, Chlamydia",
            "price": 210000,
            "is_visible": True,
        },
    ],
    "dog": [
        {
            "id": "88b0e961",
            "treatment": "Dog Neutering",
            "desc": "",
            "price": 2000000,
            "is_visible": True,
        },
        {
            "id": "f765166b",
            "treatment": "Doctor's Consultation",
            "desc": "",
            "price": 250000,
            "is_visible": True,
        },
        {
            "id": "11cb49c3",
            "treatment": "USG",
            "desc": "",
            "price": 120000,
            "is_visible": True,
        },
        {
            "id": "aa7d136e",
            "treatment": "Dog Mijor Surgery",
            "desc": "",
            "price": 900000,
            "is_visible": True,
        },
        {
            "id": "98cf0be3",
            "treatment": "Dog Major Surgery",
            "desc": "",
            "price": 1500000,
            "is_visible": True,
        },
        {
            "id": "d0fee029",
            "treatment": "DP Vaccination",
            "desc": "For Distemper and Parvovirus",
            "price": 200000,
            "is_visible": True,
        },
        {
            "id": "cb607cb3",
            "treatment": "PiBr Vaccination",
            "desc": "For Parainfluenza dan Bordetella",
            "price": 1500000,
            "is_visible": True,
        },
        {
            "id": "fdde88e7",
            "treatment": "DHLPI Vaccination",
            "desc": "For Distemper, Hepatitis, Leptospirosis, Parvovirus, dan Rabies 2",
            "price": 225000,
            "is_visible": True,
        },
        {
            "id": "2434fead",
            "treatment": "Rabies Vaccination",
            "desc": "For Ra",
            "price": 1500000,
            "is_visible": True,
        },
    ],
}
