supplies = [
    {
        "id": "0eaf059c",
        "name": "Royal Canin Kitten, Dry Food 400gr",
        "desc": "",
        "category": "Cat Food",
        "sub_category": "Kitten Food",
        "type": "Dry Food",
        "size": "400gr",
        "price": 78000,
        "stock": 10,
    },
    {
        "id": "d9bbe978",
        "name": "Royal Canin Kitten, Dry Food 2kg",
        "desc": "",
        "category": "Cat Food",
        "sub_category": "Kitten Food",
        "type": "Dry Food",
        "size": "2kg",
        "price": 348000,
        "stock": 10,
    },
    {
        "id": "ba071316",
        "name": "Royal Canin Mother & Baby Cat, Dry Food 400gr",
        "desc": "Specifically for mothers during pregnancy and lactation, and their kittens (age 1 to 4 months) during weaning.",
        "category": "Cat Food",
        "sub_category": "Mother & Baby Cat Food",
        "type": "Dry Food",
        "size": "400gr",
        "price": 74000,
        "stock": 10,
    },
    {
        "id": "562f3812",
        "name": "Royal Canin Mother & Baby Cat, Dry Food 2kg",
        "desc": "",
        "category": "Cat Food",
        "sub_category": "Mother & Baby Cat Food",
        "type": "Dry Food",
        "size": "2kg",
        "price": 335000,
        "stock": 10,
    },
    {
        "id": "798b4927",
        "name": "Whiskas Junior Repack, Kitten Dry Food 500gr",
        "desc": "",
        "category": "Cat Food",
        "sub_category": "Kitten Food",
        "type": "Dry Food",
        "size": "500gr",
        "price": 27000,
        "stock": 10,
    },
    {
        "id": "d35937f0",
        "name": "Whiskas Junior Repack, Kitten Dry Food 1kg",
        "desc": "",
        "category": "Cat Food",
        "sub_category": "Kitten Food",
        "type": "Dry Food",
        "size": "1kg",
        "price": 55000,
        "stock": 10,
    },
    {
        "id": "9daa35a4",
        "name": "Whiskas Wet Food Tuna, 400gr",
        "desc": "",
        "category": "Cat Food",
        "sub_category": "Kitten Food",
        "type": "Wet Food",
        "size": "400gr",
        "price": 25000,
        "stock": 10,
    },
    {
        "id": "9258efc6",
        "name": "Whiskas Ocean Fish Repack 1kg",
        "desc": "",
        "category": "Cat Food",
        "sub_category": "Adult Cat Food",
        "type": "Dry Food",
        "size": "1kg",
        "price": 54000,
        "stock": 10,
    },
    {
        "id": "a040bbbe",
        "name": "Royal Canin Mini Puppy, Dry Food 2kg",
        "desc": "",
        "category": "Dog Food",
        "sub_category": "Mini Puppy Dog Food",
        "type": "Dry Food",
        "size": "2kg",
        "price": 285000,
        "stock": 10,
    },
    {
        "id": "c7cb2a65",
        "name": "Royal Canin Mini Puppy, Dry Food 4kg",
        "desc": "",
        "category": "Dog Food",
        "sub_category": "Mini Puppy Dog Food",
        "type": "Dry Food",
        "size": "2kg",
        "price": 510000,
        "stock": 10,
    },
    {
        "id": "44099dac",
        "name": "Royal Canin Medium Puppy, Dry Food 4kg",
        "desc": "",
        "category": "Dog Food",
        "sub_category": "Medium Puppy Dog Food",
        "type": "Dry Food",
        "size": "4kg",
        "price": 470000,
        "stock": 10,
    },
    {
        "id": "b42bda28",
        "name": "Royal Canin Medium Puppy Pouch, Wet Food 140gr",
        "desc": "",
        "category": "Dog Food",
        "sub_category": "Medium Puppy Dog Food",
        "type": "Wet Food",
        "size": "140gr",
        "price": 25000,
        "stock": 10,
    },
    {
        "id": "72fc8fd1",
        "name": "Royal Canin Maxi Puppy, Dry Food 4kg",
        "desc": "",
        "category": "Dog Food",
        "sub_category": "Maxi Puppy Dog Food",
        "type": "Dry Food",
        "size": "4kg",
        "price": 460000,
        "stock": 10,
    },
    {
        "id": "ba613675",
        "name": "Royal Canin Maxi Puppy Pouch, Wet Food 140gr",
        "desc": "",
        "category": "Dog Food",
        "sub_category": "Maxi Puppy Dog Food",
        "type": "Wet Food",
        "size": "140gr",
        "price": 25000,
        "stock": 10,
    },
    {
        "id": "3dc83b75",
        "name": "Royal Canin Mini Adult, Dry Food 4kg",
        "desc": "For adult small breed dogs (weighing between 1 and 10 kg) - over 10 months old.",
        "category": "Dog Food",
        "sub_category": "Mini Adult Dog Food",
        "type": "Dry Food",
        "size": "4kg",
        "price": 480000,
        "stock": 10,
    },
    {
        "id": "863ac6e3",
        "name": "Royal Canin Medium Adult, Dry Food 4kg",
        "desc": "For adult medium-sized breed dogs (from 11 to 25 kg) - From 12 months to 7 years old.",
        "category": "Dog Food",
        "sub_category": "Medium Adult Dog Food",
        "type": "Dry Food",
        "size": "4kg",
        "price": 415000,
        "stock": 10,
    },
    {
        "id": "6552a3c6",
        "name": "Royal Canin Maxi Adult, Dry Food 4kg",
        "desc": "For adult large breed dogs (from 26 to 44 kg) - From 15 months to 5 years old.",
        "category": "Dog Food",
        "sub_category": "Maxi Adult Dog Food",
        "type": "Dry Food",
        "size": "4kg",
        "price": 415000,
        "stock": 10,
    },
    {
        "id": "e76f6fca",
        "name": "Pet Carrier/Pet Cargo Large",
        "desc": "",
        "category": "Pet Supplies",
        "sub_category": "-",
        "type": "-",
        "size": "Size in cm: 62 x 39 x 38",
        "price": 274000,
        "stock": 10,
    },
    {
        "id": "0b042cc6",
        "name": "Pet Cage Size Large",
        "desc": "",
        "category": "Pet Supplies",
        "sub_category": "-",
        "type": "-",
        "size": "Size in cm: 61 x 43 x 53",
        "price": 288000,
        "stock": 10,
    },
    {
        "id": "0833a7d5",
        "name": "Cat Litter Box Large",
        "desc": "With plenty of room, this litter box can easily fit kitties of up to 10kg in size. It is suitable for multi-cat household use as well!",
        "category": "Pet Supplies",
        "sub_category": "-",
        "type": "-",
        "size": "Size in cm: 57 x 44 x 38",
        "price": 385000,
        "stock": 10,
    },
]
